### ISSUE TITLE
[BUG] cannot get stakeAddress

### ISSUE THREAD

**Issue by oh-dev-life** [cardano-foundation/cardano-connect-with-wallet#37]
**Describe the bug**
whenever I reload the browser 3 to 4 times, I always receive stakeAddress = null.  Does anyone face this issue?

**Comment by oh-dev-life** [comment]
it through this when stakeAddress = null
![Screenshot 2023-03-23 at 15 24 03](https://user-images.githubusercontent.com/43344005/227147999-6a701495-d833-49bb-ab6f-286e23a4bebf.png)

**Comment by oh-dev-life** [comment]
I believe this should be updated when cardano[walletName] possibly undefined
![Screenshot 2023-03-23 at 15 58 53](https://user-images.githubusercontent.com/43344005/227153276-f81b77d9-72b2-454b-9277-f616f7fa03dd.png)

**Comment by fabianbormann** [comment]
Thx for reporting! I will try to reproduce & fix it 😊

**Comment by danielchambers** [comment]
I am getting the same when I refresh. Additionally, I get the following error:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isEnabled')`

**Comment by fabianbormann** [comment]
I'm on it and I plan to provide the new release today. Sry for the delay. I was on holiday last week

**Comment by Sotatek-DaiNguyen4** [comment]
@fabianbormann  seem it fixed, thanks 💯
