### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by web3-literally** [cardano-foundation/cardano-connect-with-wallet#43]
Thanks so much for great component to connect Cardano, it works perfectly.
But to make tranactions , there is no way by using this component, so I hope your team add that features as well
now only wallet connect functions are perfect, but with only this function, it is really difficult to develop cardano web3 project.
Best regards

**Comment by fabianbormann** [comment]
Hey @web3-literally, you could look into [lucid](https://github.com/spacebudz/lucid#basic-usage) and replace this ```const api...``` line in their example code:

```js
// Assumes you are in a browser environment
---> const api = await window.cardano.nami.enable();
lucid.selectWallet(api);
```

by ```const api = window.cardano[enabledWallet].enable();``` and you can get the enabled wallet from the useCardano hook ```const { enabledWallet } = useCardano();```. 

Another possibilty would be to look into the [meshjs libs](https://meshjs.dev/apis/transaction) those guys built amazing stuff to simplify our cardano dev lives 😉 

I hope that helps & thanks for building on Cardano! 🚀 😊

**Comment by web3-literally** [comment]
Very good!!!
Thanks so much

**Comment by web3-literally** [comment]
And how to get shelley address?
From stakeAddress, I can't do anything. please help me

**Comment by fabianbormann** [comment]
I will add a wrapper for `window.cardano.[enabledWallet].getUsedAddresses()` and `window.cardano.[enabledWallet]. getUnusedAddresses()` to the useCardano hook in the next version but until that you can call those functions in typescript from `(window as any).cardano.[enabledWallet].getUsedAddresses()`.

**Comment by fabianbormann** [comment]
I created a new issue for this feature and I try to implement it with the next version. I will close this issue here but you can follow the status in #46. 😊
