### ISSUE TITLE
Get payment addresses from useCardano hook

### ISSUE THREAD

**Issue by fabianbormann** [cardano-foundation/cardano-connect-with-wallet#46]
There are some use cases where dapps require the payment addresses of a connected wallet. Therefore, it is suggested that a wrapper will be added to the useCardano hook for both `window.cardano.[enabledWallet].getUsedAddresses()` and `window.cardano.[enabledWallet].getUnusedAddresses()` so that they will available as `{ usedAddresses, unusedAddresses } = useCardano()`.

**Comment by fabianbormann** [comment]
@web3-literally please test the latest version. You can now get the payment addresses by using:

```js
const { usedAddresses, unusedAddresses } = useCardano();
```

**Comment by web3-literally** [comment]
> 

Thanks so much for your help.
