### ISSUE TITLE
[FEATURE] Add VESPR to list supported wallets

### ISSUE THREAD

**Issue by AlexDochioiu** [cardano-foundation/cardano-connect-with-wallet#59]
The wallet can be found under "window.cardano.vespr"

**Comment by fabianbormann** [comment]
Hi @AlexDochioiu, originally the [default supportedWallets list](https://github.com/cardano-foundation/cardano-connect-with-wallet/blob/main/react/src/components/ConnectWalletButton/ConnectWalletButton.tsx#L34) was meant to be an example, as all CIP-30 compliant wallets are supported. Please just add it to your list of supported wallets using the button prop if you want to support it on your dApp. 

```js
<ConnectWalletButton supportedWallets={['vespr', 'anotherCIP30Wallet']} />
```
