### ISSUE TITLE
[Bug]: event name mismatch: "connecting" vs "isConnecting"

### ISSUE THREAD

**Issue by robinboening** [cardano-foundation/cardano-connect-with-wallet#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

An event listener "connecting" can be added using `addEventListener` function. https://github.com/cardano-foundation/cardano-connect-with-wallet/blob/main/core/index.ts#L64

The callback will never be triggered because only an event named "isConnecting" would enter the clause where you subscribe to the `isConnectingObserver`: https://github.com/cardano-foundation/cardano-connect-with-wallet/blob/main/core/index.ts#L83

### Expected Behavior

I expect `addEventListener("connecting", callback)` to trigger the callback.

### Steps To Reproduce

```
import { Wallet } from '@cardano-foundation/cardano-connect-with-wallet-core';

Wallet.addEventListener("connecting", () => {
  console.log("connecting")
});

await Wallet.connect("eternl", "mainnet");
```

**Comment by fabianbormann** [comment]
@robinboening thank you for reporting and fixing this issue ! Much appreciated 💪 (I will trigger the build pipeline and the new version should be available on npm in a few minutes)
